// Code generated by MockGen. DO NOT EDIT.
// Source: stripe.go
//
// Generated by this command:
//
//	mockgen -source=stripe.go -destination=stripe_mock_test.go -package=billing
//

// Package billing is a generated GoMock package.
package billing

import (
	context "context"
	reflect "reflect"

	v86 "github.com/stripe/stripe-go/v86"
	gomock "go.uber.org/mock/gomock"
)

// MockmeterEventCreator is a mock of meterEventCreator interface.
type MockmeterEventCreator struct {
	ctrl     *gomock.Controller
	recorder *MockmeterEventCreatorMockRecorder
	isgomock struct{}
}

// MockmeterEventCreatorMockRecorder is the mock recorder for MockmeterEventCreator.
type MockmeterEventCreatorMockRecorder struct {
	mock *MockmeterEventCreator
}

// NewMockmeterEventCreator creates a new mock instance.
func NewMockmeterEventCreator(ctrl *gomock.Controller) *MockmeterEventCreator {
	mock := &MockmeterEventCreator{ctrl: ctrl}
	mock.recorder = &MockmeterEventCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmeterEventCreator) EXPECT() *MockmeterEventCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockmeterEventCreator) Create(ctx context.Context, params *v86.BillingMeterEventCreateParams) (*v86.BillingMeterEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*v86.BillingMeterEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockmeterEventCreatorMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockmeterEventCreator)(nil).Create), ctx, params)
}
